### PR TITLE
Lxde: packages-systemd.yaml for netinstall

### PR DESCRIPTION
**Pull request by ThanosApostolou**
All the extra software is included. Some package groups may need a little change. The descriptions need to be polished as well. However, these can be done even after release. So, when this is merged (and when my desktop-settings changes get merged and reach unstable too), I will do an alpha2 to get additional feedback and ask some opinions about how groups and descriptions should look.

### CODE REVIEW

**Comment by Ste74** [comment]
Why you have set all listed files selected by default ?

**Comment by ThanosApostolou** [comment]
I want to make it as user friendly as possible. Since my intentions initially weren't to do a netinstall, but then too many users asked, I thought it would be best to have all pre-selected in order to inspire users to install everything and allow only to "experts" users to unselect what they don't like. In my opinion, even with everything selected the install is still normal (not over bloated or anything).

**Comment by Ste74** [comment]
Ok .. is your edition 😜

**Comment by ThanosApostolou** [comment]
@Ste74 Nice! Thx! Is it possible to push the changes you accepted on desktop-settings into manjaro-lxde-settings in unstable branch in order to do a quick alpha2 release? If it's not too much trouble for you...

**Comment by Ste74** [comment]
Sync the repo 😉 is already in unstable 😉

**Pull request merged**
