### PR TITLE
overhauled chrootcfg-systemd for lxqt net install

### PR DESCRIPTION
**Pull request by excalibur1234**
i would like to continue to work on this in the future. 

@philmmanjaro 
commit access to this repo (and [the iso-profile repo](https://github.com/manjaro/iso-profiles)) would be great!

### CODE REVIEW

**Comment by excalibur1234** [comment]
i moved compton to WM category as suggested.

Ste74 will push a working version of juffed-qt5 to the stable repos. then, everything works as far as i can see.

ready for merge?
if nobody merges it within the next 24h, i will merge it.

**Comment by udeved** [comment]
You've got also direct access to this repo. ;)

**Comment by Ste74** [comment]
@udeved , ot : when you or Bernhard or other  commit in other repo example in community merge master branch what you mean? /ot

**Comment by udeved** [comment]
Didn't understand that @Ste74 
Can you describe again please?

**Comment by Ste74** [comment]
If you see in community repo the last commit : in the description I read merge master branch bla bla ..

**Comment by udeved** [comment]
Ah, I think I know what you mean.
This happens, if you had uncommitted changes in the local copy, and do a pull after you committed your changes. Or, if you forgot to pull before starting some work. :)

**Comment by Ste74** [comment]
Ah :D ... thank you ;) now I understand :D

**Comment by excalibur1234** [comment]
the process of doing a "git pull" AFTER you have changed something in your local repo is called a "rebase" of your local git repo. it can create a merge conflict.

in the beginning, i was confused when people wanted me to "rebase". i first had to look up what that meant...

**Comment by Ste74** [comment]
@excalibur1234 : juffed is already in testing but now i pushed in stable too .. 😉

**Pull request merged**
